id: PEF4FDA89
initial_creation_type: ocr
source_metadata:
  volumes:
    3cfdd2a1861f4babb08480812d380ef9:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: འཕགས་པ་ཆོས་བཞི་པའི་རྣམ་པར་བཤད་པ།
      total_pages: 1498
      volume_number: 65
