id: DD43C7AF2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-11T09:48:53+00:00'
last_modified: '2022-05-27T16:03:43.308330+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    9d14:
      image_group_id: I1PD95910
      title: འཕགས་པ་ཆོས་བཞི་པའི་རྣམ་པར་བཤད་པ།
      total_pages: 1498
      order: 65
      base_file: 9d14.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
